### PR TITLE
fix: Fix default extensions

### PR DESCRIPTION
**Pull request by johnstonmatt**
The default postgresql extensions which should be installed in this container will not be installed unless the package repository for Postgresql apt has been enabled as shown here.

https://wiki.postgresql.org/wiki/Apt

### CODE REVIEW

**Comment by johnstonmatt** [comment]
To expand a bit on this, it is not possible to install any of the dependencies beginning with `postgresql-` before installing `postgresql-common`, and running this script: 
https://github.com/credativ/postgresql-common/blob/master/pgdg/apt.postgresql.org.sh

The downstream impact of this is that in every current container used by cnpg `pgvector` ( and I assume `pg-failover-slots`, and `pgaudit` ) are not available for use with `CREATE EXTENSION`. 

Without this change `CREATE EXTENSION vector` will fail.

**Comment by johnstonmatt** [comment]
@gbartolini I think you might be the best person to look this one over

**Comment by NiccoloFei** [comment]
@johnstonmatt the reason ca-certificates/postgresql-common and the PGDG repositoriy are not part of the Dockerfile is because that's already done as part of the `postgres` base image we depend on (e.g https://github.com/docker-library/postgres/blob/master/16/bullseye/Dockerfile for PG16).

> The downstream impact of this is that in every current container used by cnpg pgvector ( and I assume pg-failover-slots, and pgaudit ) are not available for use with CREATE EXTENSION.
Without this change CREATE EXTENSION vector will fail, and with this change it will succeed.

That's very weird, the packages of those extensions are definitely installed in the container image.
```
$ docker run --rm -it ghcr.io/cloudnative-pg/postgresql:16 bash
postgres@27ceb5c27071:/$ dpkg -l | grep postgres
ii  postgresql-16                   16.2-1.pgdg110+2             amd64        The World's Most Advanced Open Source Relational Database
ii  postgresql-16-pg-failover-slots 1.0.1-2.pgdg110+1            amd64        High-availability support for PostgreSQL logical replication
ii  postgresql-16-pgaudit           16.0-1.pgdg110+1             amd64        PostgreSQL Audit Extension
ii  postgresql-16-pgvector          0.6.0-1.pgdg110+1            amd64        Open-source vector similarity search for Postgres
ii  postgresql-client-16            16.2-1.pgdg110+2             amd64        front-end programs for PostgreSQL 16
ii  postgresql-client-common        257.pgdg110+1                all          manager for multiple PostgreSQL client versions
ii  postgresql-common               257.pgdg110+1                all          PostgreSQL database-cluster manager
```

Regarding pg_vector, `CREATE EXTENSION vector` should work seamlessly (you don't have to add extension in the shared_preload_libraries ).

`pg-failover-slots` and `pgaudit` are part of the cnpg [managed extensions](https://cloudnative-pg.io/documentation/1.22/postgresql_conf/#managed-extensions), so you can just add their configuration parameters in the cluster spec and the operator will transparently enable them by adding them to `shared_preload_libraries`, restarting the pods if needed etc..

**Comment by johnstonmatt** [comment]
@NiccoloFei were you able to reproduce the error I mentioned where `CREATE EXTENSION vector` failed? If you'd like me to do more work to demonstrate I'd be happy to

**Comment by NiccoloFei** [comment]
@johnstonmatt No I haven't been able to reproduce that issue. Please, if you could provide some steps that would be very helpful

**Pull request closed without merging**
